/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BKCalculater;

import org.json.JSONObject;

import com.bunker.bkframework.server.BKLauncher;
import com.bunker.bkframework.server.framework_api.text.TextJSONBusiness;
import com.bunker.bkframework.server.framework_api.text.TextServerCore;
import com.bunker.bkframework.server.working.WorkConstants;
import com.bunker.bkframework.server.working.WorkContainer;

public class Library {    
    public static void main(String []args) {
    	BKLauncher.init();
    	
    	//코어 설정
    	WorkContainer container = new WorkContainer("my work container");
    	try {
			container.loadWorkings("BKCalculater");
		} catch (InstantiationException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		}
    	
    	TextServerCore textCore = new TextServerCore();
    	BKLauncher.getLauncher().initCore(textCore);
		TextJSONBusiness business = new TextJSONBusiness(container);
		textCore.setPeer(business);
    	
    	//API 설정
    	container.setJSONParam("work_json");
		
		//클라이언트 테스트
		JSONObject json = new JSONObject();
		json.put(WorkConstants.WORKING, "my-operator");
		json.put("a", 1);
		json.put("b", 10);
		System.out.println(textCore.doWork(json.toString()));
    }
}
